name: "Bug Report"
description: "Report a bug or issue with the application."
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve! Please complete the following sections as thoroughly as possible to assist us in diagnosing the issue.

  - type: input
    id: summary
    attributes:
      label: "Bug Summary"
      description: "Provide a brief description of the bug."
      placeholder: "Short summary of the bug"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Describe the steps taken to encounter this bug."
      placeholder: "1. Go to...\n2. Click on...\n3. Observe..."
    validations:
      required: true
