name: "Bug Report"
description: "Report a bug or issue with the application."
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve! Please complete the following sections as thoroughly as possible to assist us in diagnosing the issue.

  - type: input
    id: summary
    attributes:
      label: "Bug Summary"
      description: "Provide a brief description of the bug."
      placeholder: "Short summary of the bug"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Describe the steps taken to encounter this bug."
      placeholder: "1. Go to...\n2. Click on...\n3. Observe..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "Explain what you expected to happen."
      placeholder: "The expected outcome..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually happened when you encountered the bug."
      placeholder: "What actually happened..."
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: "Environment"
      description: "Specify the environment where the bug occurred."
      options:
        - Development
        - Staging
        - Production
      default: "Production"

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context and Screenshots"
      description: "Provide any other information that might help in diagnosing the issue, including relevant screenshots or logs."
